FROM golang:1.18-alpine

RUN set -x \
&& apk add --no-cache git musl-dev gcc npm make gzip

ARG NO_CACHE

RUN set -x \
&& mkdir -p /go/src/github.com/kuoss \
&& cd       /go/src/github.com/kuoss \
&& git clone --depth=1 https://github.com/kuoss/lethe.git \
&& cd lethe \
&& go install -v github.com/cosmtrek/air@latest
&& go mod tidy

WORKDIR /go/src/github.com/kuoss/lethe
