// Code generated by goyacc -o letheql/parser/generated_parser.y.go letheql/parser/generated_parser.y. DO NOT EDIT.

//line letheql/parser/generated_parser.y:15
package parser

import (
	__yyfmt__ "fmt"
	"math"
	"strconv"
	"time"

	"github.com/prometheus/prometheus/model/labels"
	"github.com/prometheus/prometheus/model/value"
) //line letheql/parser/generated_parser.y:15

//line letheql/parser/generated_parser.y:28
type yySymType struct {
	yys      int
	node     Node
	item     Item
	matchers []*labels.Matcher
	matcher  *labels.Matcher
	label    labels.Label
	labels   labels.Labels
	lblList  []labels.Label
	strings  []string
	series   []SequenceValue
	uint     uint64
	float    float64
	duration time.Duration
}

const EQL = 57346
const BLANK = 57347
const COLON = 57348
const COMMA = 57349
const COMMENT = 57350
const DURATION = 57351
const EOF = 57352
const ERROR = 57353
const IDENTIFIER = 57354
const LEFT_BRACE = 57355
const LEFT_BRACKET = 57356
const LEFT_PAREN = 57357
const METRIC_IDENTIFIER = 57358
const NUMBER = 57359
const RIGHT_BRACE = 57360
const RIGHT_BRACKET = 57361
const RIGHT_PAREN = 57362
const SEMICOLON = 57363
const SPACE = 57364
const STRING = 57365
const TIMES = 57366
const operatorsStart = 57367
const ADD = 57368
const DIV = 57369
const EQLC = 57370
const EQL_REGEX = 57371
const GTE = 57372
const GTR = 57373
const LAND = 57374
const LOR = 57375
const LSS = 57376
const LTE = 57377
const LUNLESS = 57378
const MOD = 57379
const MUL = 57380
const NEQ = 57381
const NEQ_REGEX = 57382
const PIPE_EQL = 57383
const PIPE_REGEX = 57384
const POW = 57385
const SUB = 57386
const AT = 57387
const ATAN2 = 57388
const operatorsEnd = 57389
const aggregatorsStart = 57390
const AVG = 57391
const BOTTOMK = 57392
const COUNT = 57393
const COUNT_VALUES = 57394
const GROUP = 57395
const MAX = 57396
const MIN = 57397
const QUANTILE = 57398
const STDDEV = 57399
const STDVAR = 57400
const SUM = 57401
const TOPK = 57402
const aggregatorsEnd = 57403
const keywordsStart = 57404
const BOOL = 57405
const BY = 57406
const GROUP_LEFT = 57407
const GROUP_RIGHT = 57408
const IGNORING = 57409
const OFFSET = 57410
const ON = 57411
const WITHOUT = 57412
const keywordsEnd = 57413
const preprocessorStart = 57414
const START = 57415
const END = 57416
const preprocessorEnd = 57417
const startSymbolsStart = 57418
const START_METRIC = 57419
const START_SERIES_DESCRIPTION = 57420
const START_EXPRESSION = 57421
const START_METRIC_SELECTOR = 57422
const startSymbolsEnd = 57423

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"EQL",
	"BLANK",
	"COLON",
	"COMMA",
	"COMMENT",
	"DURATION",
	"EOF",
	"ERROR",
	"IDENTIFIER",
	"LEFT_BRACE",
	"LEFT_BRACKET",
	"LEFT_PAREN",
	"METRIC_IDENTIFIER",
	"NUMBER",
	"RIGHT_BRACE",
	"RIGHT_BRACKET",
	"RIGHT_PAREN",
	"SEMICOLON",
	"SPACE",
	"STRING",
	"TIMES",
	"operatorsStart",
	"ADD",
	"DIV",
	"EQLC",
	"EQL_REGEX",
	"GTE",
	"GTR",
	"LAND",
	"LOR",
	"LSS",
	"LTE",
	"LUNLESS",
	"MOD",
	"MUL",
	"NEQ",
	"NEQ_REGEX",
	"PIPE_EQL",
	"PIPE_REGEX",
	"POW",
	"SUB",
	"AT",
	"ATAN2",
	"operatorsEnd",
	"aggregatorsStart",
	"AVG",
	"BOTTOMK",
	"COUNT",
	"COUNT_VALUES",
	"GROUP",
	"MAX",
	"MIN",
	"QUANTILE",
	"STDDEV",
	"STDVAR",
	"SUM",
	"TOPK",
	"aggregatorsEnd",
	"keywordsStart",
	"BOOL",
	"BY",
	"GROUP_LEFT",
	"GROUP_RIGHT",
	"IGNORING",
	"OFFSET",
	"ON",
	"WITHOUT",
	"keywordsEnd",
	"preprocessorStart",
	"START",
	"END",
	"preprocessorEnd",
	"startSymbolsStart",
	"START_METRIC",
	"START_SERIES_DESCRIPTION",
	"START_EXPRESSION",
	"START_METRIC_SELECTOR",
	"startSymbolsEnd",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line letheql/parser/generated_parser.y:754

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 35,
	1, 134,
	10, 134,
	22, 134,
	-2, 0,
	-1, 58,
	2, 146,
	15, 146,
	64, 146,
	70, 146,
	-2, 100,
	-1, 59,
	2, 147,
	15, 147,
	64, 147,
	70, 147,
	-2, 101,
	-1, 60,
	2, 148,
	15, 148,
	64, 148,
	70, 148,
	-2, 103,
	-1, 61,
	2, 149,
	15, 149,
	64, 149,
	70, 149,
	-2, 104,
	-1, 62,
	2, 150,
	15, 150,
	64, 150,
	70, 150,
	-2, 105,
	-1, 63,
	2, 151,
	15, 151,
	64, 151,
	70, 151,
	-2, 110,
	-1, 64,
	2, 152,
	15, 152,
	64, 152,
	70, 152,
	-2, 112,
	-1, 65,
	2, 153,
	15, 153,
	64, 153,
	70, 153,
	-2, 114,
	-1, 66,
	2, 154,
	15, 154,
	64, 154,
	70, 154,
	-2, 115,
	-1, 67,
	2, 155,
	15, 155,
	64, 155,
	70, 155,
	-2, 116,
	-1, 68,
	2, 156,
	15, 156,
	64, 156,
	70, 156,
	-2, 117,
	-1, 69,
	2, 157,
	15, 157,
	64, 157,
	70, 157,
	-2, 118,
	-1, 198,
	12, 204,
	13, 204,
	16, 204,
	17, 204,
	23, 204,
	26, 204,
	32, 204,
	33, 204,
	36, 204,
	44, 204,
	49, 204,
	50, 204,
	51, 204,
	52, 204,
	53, 204,
	54, 204,
	55, 204,
	56, 204,
	57, 204,
	58, 204,
	59, 204,
	60, 204,
	64, 204,
	68, 204,
	70, 204,
	73, 204,
	74, 204,
	-2, 0,
	-1, 199,
	12, 204,
	13, 204,
	16, 204,
	17, 204,
	23, 204,
	26, 204,
	32, 204,
	33, 204,
	36, 204,
	44, 204,
	49, 204,
	50, 204,
	51, 204,
	52, 204,
	53, 204,
	54, 204,
	55, 204,
	56, 204,
	57, 204,
	58, 204,
	59, 204,
	60, 204,
	64, 204,
	68, 204,
	70, 204,
	73, 204,
	74, 204,
	-2, 0,
	-1, 223,
	19, 202,
	-2, 0,
	-1, 273,
	19, 203,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 668

var yyAct = [...]int16{
	279, 37, 227, 148, 269, 268, 156, 116, 77, 105,
	104, 107, 196, 282, 197, 198, 199, 108, 129, 264,
	103, 160, 263, 124, 262, 155, 6, 188, 229, 178,
	57, 179, 82, 84, 103, 277, 271, 283, 239, 161,
	276, 258, 245, 93, 94, 261, 285, 106, 187, 99,
	100, 102, 83, 275, 257, 111, 181, 112, 241, 242,
	109, 110, 243, 99, 150, 102, 180, 182, 183, 184,
	125, 151, 256, 280, 101, 230, 232, 234, 235, 236,
	244, 246, 249, 250, 251, 252, 253, 113, 101, 231,
	233, 237, 238, 240, 247, 248, 159, 219, 109, 254,
	255, 2, 3, 4, 5, 72, 149, 162, 118, 107,
	79, 172, 166, 169, 164, 108, 165, 168, 117, 151,
	78, 274, 33, 7, 259, 284, 185, 195, 151, 186,
	167, 194, 200, 201, 202, 203, 204, 205, 206, 207,
	208, 209, 210, 211, 212, 213, 214, 215, 216, 217,
	193, 81, 34, 218, 130, 131, 132, 133, 134, 135,
	136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
	146, 147, 224, 163, 118, 1, 223, 176, 10, 154,
	151, 229, 175, 260, 117, 190, 220, 221, 74, 222,
	115, 239, 192, 174, 159, 245, 272, 159, 265, 226,
	79, 266, 267, 160, 121, 270, 160, 48, 47, 120,
	78, 241, 242, 73, 8, 243, 76, 123, 35, 122,
	119, 161, 46, 45, 161, 256, 44, 273, 230, 232,
	234, 235, 236, 244, 246, 249, 250, 251, 252, 253,
	128, 43, 231, 233, 237, 238, 240, 247, 248, 42,
	157, 158, 254, 255, 56, 41, 126, 9, 9, 170,
	278, 40, 127, 39, 38, 281, 51, 72, 49, 53,
	22, 52, 152, 191, 171, 80, 189, 54, 225, 286,
	70, 75, 153, 287, 55, 228, 18, 19, 177, 50,
	20, 114, 0, 0, 0, 0, 0, 0, 71, 0,
	0, 0, 0, 58, 59, 60, 61, 62, 63, 64,
	65, 66, 67, 68, 69, 0, 0, 0, 13, 0,
	0, 0, 24, 0, 30, 0, 0, 31, 32, 36,
	103, 51, 72, 0, 53, 22, 52, 0, 0, 0,
	0, 0, 54, 84, 0, 70, 0, 0, 0, 0,
	0, 18, 19, 93, 94, 20, 0, 0, 0, 99,
	0, 102, 83, 71, 0, 0, 0, 0, 58, 59,
	60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
	0, 0, 0, 13, 101, 0, 0, 24, 0, 30,
	0, 0, 31, 32, 51, 72, 0, 53, 22, 52,
	0, 0, 0, 0, 0, 54, 0, 0, 70, 0,
	0, 0, 0, 0, 18, 19, 0, 0, 20, 0,
	0, 0, 0, 17, 72, 0, 71, 22, 0, 0,
	0, 58, 59, 60, 61, 62, 63, 64, 65, 66,
	67, 68, 69, 18, 19, 0, 13, 20, 0, 0,
	24, 0, 30, 17, 33, 31, 32, 22, 0, 0,
	11, 12, 14, 15, 16, 21, 23, 25, 26, 27,
	28, 29, 0, 18, 19, 13, 0, 20, 0, 24,
	0, 30, 0, 0, 31, 32, 0, 0, 0, 0,
	11, 12, 14, 15, 16, 21, 23, 25, 26, 27,
	28, 29, 0, 0, 103, 13, 0, 0, 0, 24,
	173, 30, 0, 0, 31, 32, 82, 84, 85, 0,
	86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
	96, 97, 98, 99, 100, 102, 83, 0, 0, 0,
	0, 0, 0, 103, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 82, 84, 85, 101, 86,
	87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
	97, 98, 99, 100, 102, 83, 0, 0, 103, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	82, 84, 85, 0, 86, 87, 88, 101, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 102,
	83, 0, 0, 103, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 82, 84, 85, 0, 86,
	87, 0, 101, 90, 91, 0, 93, 94, 95, 96,
	97, 98, 99, 100, 102, 83, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 101,
}

var yyPact = [...]int16{
	24, 113, 441, 441, 319, 411, -1000, -1000, -1000, 109,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 198, -1000, 149, -1000, 529, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	45, 83, -1000, 382, -1000, 382, 92, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 172, -1000, -1000, 202, -1000, -1000, 215, -1000,
	1, -1000, -45, -45, -45, -45, -45, -45, -45, -45,
	-45, -45, -45, -45, -45, -45, -45, -45, -45, -45,
	-45, 62, 177, 171, 83, -53, -1000, 115, 115, 254,
	-1000, 490, 20, -1000, 175, -1000, -1000, 27, -1000, -1000,
	108, -1000, 25, -1000, 180, 382, -1000, -55, -50, -1000,
	382, 382, 382, 382, 382, 382, 382, 382, 382, 382,
	382, 382, 382, 382, 382, 382, 382, 382, -1000, 110,
	-1000, -1000, -1000, 82, -1000, -1000, -1000, -1000, -1000, -1000,
	79, 79, 170, -1000, -1000, -1000, -1000, 179, -1000, -1000,
	34, -1000, 529, -1000, -1000, 106, -1000, 22, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-2, -5, -1000, -1000, -1000, 316, 115, 115, 115, 115,
	20, 20, 6, 6, 6, 599, 564, 6, 6, 599,
	20, 20, 6, 6, 6, 6, 20, 316, -1000, 16,
	-1000, -1000, -1000, 119, -1000, 33, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 382, -1000,
	-1000, -1000, -1000, 56, 56, -11, -1000, -1000, -1000, -1000,
	-1000, -1000, 18, 123, -1000, -1000, 26, -1000, 529, -1000,
	-1000, -1000, 56, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 291, 7, 289, 2, 288, 285, 254, 284, 282,
	178, 214, 281, 8, 278, 4, 5, 276, 275, 0,
	25, 273, 6, 272, 268, 264, 10, 70, 263, 262,
	1, 261, 259, 9, 256, 30, 255, 249, 241, 240,
	226, 223, 222, 208, 207, 3, 196, 175, 152,
}

var yyR1 = [...]int8{
	0, 47, 47, 47, 47, 47, 47, 47, 30, 30,
	30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
	25, 25, 25, 25, 26, 26, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 27, 29, 29, 39, 39,
	34, 34, 34, 34, 15, 15, 15, 15, 14, 14,
	14, 4, 4, 31, 33, 33, 32, 32, 32, 40,
	38, 38, 38, 24, 24, 24, 9, 9, 36, 42,
	42, 42, 42, 42, 43, 44, 44, 44, 35, 35,
	35, 1, 1, 1, 2, 2, 2, 2, 11, 11,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 10, 10, 10, 10, 12, 12, 12, 13,
	13, 13, 13, 48, 18, 18, 18, 18, 17, 17,
	17, 17, 17, 21, 21, 21, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 8, 8, 5, 5, 5,
	5, 5, 5, 37, 20, 22, 22, 23, 23, 19,
	45, 41, 46, 46, 16, 16,
}

var yyR2 = [...]int8{
	0, 2, 2, 2, 2, 2, 2, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	3, 3, 2, 2, 2, 2, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 1, 0, 1, 3, 3,
	1, 1, 3, 3, 3, 4, 2, 1, 3, 1,
	2, 1, 1, 2, 3, 2, 3, 1, 2, 3,
	3, 4, 3, 3, 5, 3, 1, 1, 4, 6,
	6, 5, 4, 3, 2, 2, 1, 1, 3, 4,
	2, 3, 1, 2, 3, 3, 2, 1, 2, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 3, 4, 2, 0, 3, 1, 2, 3,
	3, 2, 1, 2, 0, 3, 2, 1, 1, 3,
	1, 3, 4, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
	1, 1, 0, 1, 0, 1,
}

var yyChk = [...]int16{
	-1000, -47, 77, 78, 79, 80, 2, 10, -11, -7,
	-10, 49, 50, 64, 51, 52, 53, 12, 32, 33,
	36, 54, 16, 55, 68, 56, 57, 58, 59, 60,
	70, 73, 74, 13, -48, -11, 10, -30, -25, -28,
	-31, -36, -37, -38, -40, -41, -42, -43, -44, -24,
	-3, 12, 17, 15, 23, -8, -7, -35, 49, 50,
	51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
	26, 44, 13, -44, -10, -12, 18, -13, 12, 2,
	-18, 2, 26, 46, 27, 28, 30, 31, 32, 33,
	34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
	44, 68, 45, 14, -26, -33, 2, 64, 70, 15,
	-33, -30, -30, -35, -1, 18, -2, 12, 2, 18,
	7, 2, 4, 2, 22, -27, -34, -29, -39, 63,
	-27, -27, -27, -27, -27, -27, -27, -27, -27, -27,
	-27, -27, -27, -27, -27, -27, -27, -27, -45, 44,
	2, 9, -23, -9, 2, -20, -22, 73, 74, 17,
	26, 44, -45, 2, -33, -26, -15, 15, 2, -15,
	-32, 20, -30, 20, 18, 7, 2, -5, 2, 4,
	39, 29, 40, 41, 42, 18, -13, 23, 2, -17,
	5, -21, 12, -20, -22, -30, 67, 69, 65, 66,
	-30, -30, -30, -30, -30, -30, -30, -30, -30, -30,
	-30, -30, -30, -30, -30, -30, -30, -30, -45, 15,
	-20, -20, 19, 6, 2, -14, 20, -4, -6, 2,
	49, 63, 50, 64, 51, 52, 53, 65, 66, 12,
	67, 32, 33, 36, 54, 16, 55, 68, 69, 56,
	57, 58, 59, 60, 73, 74, 46, 20, 7, 18,
	-2, 23, 2, 24, 24, -22, -15, -15, -16, -15,
	-16, 20, -46, -45, 2, 20, 7, 2, -30, -19,
	17, -19, 24, 19, 2, 20, -4, -19,
}

var yyDef = [...]int16{
	0, -2, 125, 125, 0, 0, 7, 6, 1, 125,
	99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
	109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
	119, 120, 121, 0, 2, -2, 3, 4, 8, 9,
	10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
	0, 106, 193, 0, 201, 0, 86, 87, -2, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	185, 186, 0, 5, 98, 0, 124, 127, 0, 132,
	133, 137, 46, 46, 46, 46, 46, 46, 46, 46,
	46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
	46, 0, 0, 0, 0, 22, 23, 0, 0, 0,
	63, 0, 84, 85, 0, 90, 92, 0, 97, 122,
	0, 128, 0, 131, 136, 0, 45, 50, 51, 47,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 70, 0,
	72, 200, 73, 0, 75, 197, 198, 76, 77, 194,
	0, 0, 0, 83, 20, 21, 24, 0, 57, 25,
	0, 65, 67, 69, 88, 0, 93, 0, 96, 187,
	188, 189, 190, 191, 192, 123, 126, 129, 130, 135,
	138, 140, 143, 144, 145, 26, 0, 0, -2, -2,
	27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
	37, 38, 39, 40, 41, 42, 43, 44, 71, 0,
	195, 196, 78, -2, 82, 0, 56, 59, 61, 62,
	158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
	168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
	178, 179, 180, 181, 182, 183, 184, 64, 68, 89,
	91, 94, 95, 0, 0, 0, 48, 49, 52, 205,
	53, 74, 0, -2, 81, 54, 0, 60, 66, 139,
	199, 141, 0, 79, 80, 55, 58, 142,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:176
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].labels
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:179
		{
			yylex.(*parser).addParseErrf(PositionRange{}, "no expression found in input")
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:181
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].node
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:183
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:186
		{
			yylex.(*parser).unexpected("", "")
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:209
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, yyDollar[2].node, yyDollar[3].node)
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:211
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, yyDollar[3].node, yyDollar[2].node)
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:213
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, &AggregateExpr{}, yyDollar[2].node)
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:215
		{
			yylex.(*parser).unexpected("aggregation", "")
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, &AggregateExpr{}, Expressions{})
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:223
		{
			yyVAL.node = &AggregateExpr{
				Grouping: yyDollar[2].strings,
			}
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:229
		{
			yyVAL.node = &AggregateExpr{
				Grouping: yyDollar[2].strings,
				Without:  true,
			}
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:242
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:243
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:244
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:245
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:246
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:247
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 32:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:248
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:249
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:250
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:251
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:252
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:253
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:254
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:255
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 40:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:256
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 41:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:257
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 42:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:258
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:259
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 44:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:260
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 46:
		yyDollar = yyS[yypt-0 : yypt+1]
//line letheql/parser/generated_parser.y:268
		{
			yyVAL.node = &BinaryExpr{
				VectorMatching: &VectorMatching{Card: CardOneToOne},
			}
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:273
		{
			yyVAL.node = &BinaryExpr{
				VectorMatching: &VectorMatching{Card: CardOneToOne},
				ReturnBool:     true,
			}
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:281
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.MatchingLabels = yyDollar[3].strings
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:286
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.MatchingLabels = yyDollar[3].strings
			yyVAL.node.(*BinaryExpr).VectorMatching.On = true
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:296
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.Card = CardManyToOne
			yyVAL.node.(*BinaryExpr).VectorMatching.Include = yyDollar[3].strings
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:302
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.Card = CardOneToMany
			yyVAL.node.(*BinaryExpr).VectorMatching.Include = yyDollar[3].strings
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:311
		{
			yyVAL.strings = yyDollar[2].strings
		}
	case 55:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:313
		{
			yyVAL.strings = yyDollar[2].strings
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:315
		{
			yyVAL.strings = []string{}
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:317
		{
			yylex.(*parser).unexpected("grouping opts", "\"(\"")
			yyVAL.strings = nil
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:323
		{
			yyVAL.strings = append(yyDollar[1].strings, yyDollar[3].item.Val)
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:325
		{
			yyVAL.strings = []string{yyDollar[1].item.Val}
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:327
		{
			yylex.(*parser).unexpected("grouping opts", "\",\" or \")\"")
			yyVAL.strings = yyDollar[1].strings
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:331
		{
			if !isLabel(yyDollar[1].item.Val) {
				yylex.(*parser).unexpected("grouping opts", "label")
			}
			yyVAL.item = yyDollar[1].item
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:338
		{
			yylex.(*parser).unexpected("grouping opts", "label")
			yyVAL.item = Item{}
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:346
		{
			fn, exist := getFunction(yyDollar[1].item.Val)
			if !exist {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "unknown function with name %q", yyDollar[1].item.Val)
			}
			yyVAL.node = &Call{
				Func: fn,
				Args: yyDollar[2].node.(Expressions),
				PosRange: PositionRange{
					Start: yyDollar[1].item.Pos,
					End:   yylex.(*parser).lastClosing,
				},
			}
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:363
		{
			yyVAL.node = yyDollar[2].node
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:365
		{
			yyVAL.node = Expressions{}
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:369
		{
			yyVAL.node = append(yyDollar[1].node.(Expressions), yyDollar[3].node.(Expr))
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:371
		{
			yyVAL.node = Expressions{yyDollar[1].node.(Expr)}
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:373
		{
			yylex.(*parser).addParseErrf(yyDollar[2].item.PositionRange(), "trailing commas not allowed in function call args")
			yyVAL.node = yyDollar[1].node
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:384
		{
			yyVAL.node = &ParenExpr{Expr: yyDollar[2].node.(Expr), PosRange: mergeRanges(&yyDollar[1].item, &yyDollar[3].item)}
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:392
		{
			yylex.(*parser).addOffset(yyDollar[1].node, yyDollar[3].duration)
			yyVAL.node = yyDollar[1].node
		}
	case 71:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:397
		{
			yylex.(*parser).addOffset(yyDollar[1].node, -yyDollar[4].duration)
			yyVAL.node = yyDollar[1].node
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:402
		{
			yylex.(*parser).unexpected("offset", "duration")
			yyVAL.node = yyDollar[1].node
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:409
		{
			yylex.(*parser).setTimestamp(yyDollar[1].node, yyDollar[3].float)
			yyVAL.node = yyDollar[1].node
		}
	case 74:
		yyDollar = yyS[yypt-5 : yypt+1]
//line letheql/parser/generated_parser.y:414
		{
			yylex.(*parser).setAtModifierPreprocessor(yyDollar[1].node, yyDollar[3].item)
			yyVAL.node = yyDollar[1].node
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:419
		{
			yylex.(*parser).unexpected("@", "timestamp")
			yyVAL.node = yyDollar[1].node
		}
	case 78:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:429
		{
			var errMsg string
			vs, ok := yyDollar[1].node.(*VectorSelector)
			if !ok {
				errMsg = "ranges only allowed for vector selectors"
			} else if vs.OriginalOffset != 0 {
				errMsg = "no offset modifiers allowed before range"
			} else if vs.Timestamp != nil {
				errMsg = "no @ modifiers allowed before range"
			}

			if errMsg != "" {
				errRange := mergeRanges(&yyDollar[2].item, &yyDollar[4].item)
				yylex.(*parser).addParseErrf(errRange, errMsg)
			}

			yyVAL.node = &MatrixSelector{
				VectorSelector: yyDollar[1].node.(Expr),
				Range:          yyDollar[3].duration,
				EndPos:         yylex.(*parser).lastClosing,
			}
		}
	case 79:
		yyDollar = yyS[yypt-6 : yypt+1]
//line letheql/parser/generated_parser.y:454
		{
			yyVAL.node = &SubqueryExpr{
				Expr:  yyDollar[1].node.(Expr),
				Range: yyDollar[3].duration,
				Step:  yyDollar[5].duration,

				EndPos: yyDollar[6].item.Pos + 1,
			}
		}
	case 80:
		yyDollar = yyS[yypt-6 : yypt+1]
//line letheql/parser/generated_parser.y:464
		{
			yylex.(*parser).unexpected("subquery selector", "\"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 81:
		yyDollar = yyS[yypt-5 : yypt+1]
//line letheql/parser/generated_parser.y:466
		{
			yylex.(*parser).unexpected("subquery selector", "duration or \"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 82:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:468
		{
			yylex.(*parser).unexpected("subquery or range", "\":\" or \"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:470
		{
			yylex.(*parser).unexpected("subquery selector", "duration")
			yyVAL.node = yyDollar[1].node
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:480
		{
			if nl, ok := yyDollar[2].node.(*NumberLiteral); ok {
				if yyDollar[1].item.Typ == SUB {
					nl.Val *= -1
				}
				nl.PosRange.Start = yyDollar[1].item.Pos
				yyVAL.node = nl
			} else {
				yyVAL.node = &UnaryExpr{Op: yyDollar[1].item.Typ, Expr: yyDollar[2].node.(Expr), StartPos: yyDollar[1].item.Pos}
			}
		}
	case 85:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:498
		{
			vs := yyDollar[2].node.(*VectorSelector)
			vs.PosRange = mergeRanges(&yyDollar[1].item, vs)
			vs.Name = yyDollar[1].item.Val
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:506
		{
			vs := &VectorSelector{
				Name:          yyDollar[1].item.Val,
				LabelMatchers: []*labels.Matcher{},
				PosRange:      yyDollar[1].item.PositionRange(),
			}
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:516
		{
			vs := yyDollar[1].node.(*VectorSelector)
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:524
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: yyDollar[2].matchers,
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[3].item),
			}
		}
	case 89:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:531
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: yyDollar[2].matchers,
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[4].item),
			}
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:538
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: []*labels.Matcher{},
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[2].item),
			}
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:547
		{
			if yyDollar[1].matchers != nil {
				yyVAL.matchers = append(yyDollar[1].matchers, yyDollar[3].matcher)
			} else {
				yyVAL.matchers = yyDollar[1].matchers
			}
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:555
		{
			yyVAL.matchers = []*labels.Matcher{yyDollar[1].matcher}
		}
	case 93:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:557
		{
			yylex.(*parser).unexpected("label matching", "\",\" or \"}\"")
			yyVAL.matchers = yyDollar[1].matchers
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:561
		{
			yyVAL.matcher = yylex.(*parser).newLabelMatcher(yyDollar[1].item, yyDollar[2].item, yyDollar[3].item)
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:563
		{
			yylex.(*parser).unexpected("label matching", "string")
			yyVAL.matcher = nil
		}
	case 96:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:565
		{
			yylex.(*parser).unexpected("label matching", "label matching operator")
			yyVAL.matcher = nil
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:567
		{
			yylex.(*parser).unexpected("label matching", "identifier or \"}\"")
			yyVAL.matcher = nil
		}
	case 98:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:575
		{
			b := labels.NewBuilder(yyDollar[2].labels)
			b.Set(labels.MetricName, yyDollar[1].item.Val)
			yyVAL.labels = b.Labels(labels.EmptyLabels())
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:577
		{
			yyVAL.labels = yyDollar[1].labels
		}
	case 122:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:584
		{
			yyVAL.labels = labels.New(yyDollar[2].lblList...)
		}
	case 123:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:586
		{
			yyVAL.labels = labels.New(yyDollar[2].lblList...)
		}
	case 124:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:588
		{
			yyVAL.labels = labels.New()
		}
	case 125:
		yyDollar = yyS[yypt-0 : yypt+1]
//line letheql/parser/generated_parser.y:590
		{
			yyVAL.labels = labels.New()
		}
	case 126:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:594
		{
			yyVAL.lblList = append(yyDollar[1].lblList, yyDollar[3].label)
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:596
		{
			yyVAL.lblList = []labels.Label{yyDollar[1].label}
		}
	case 128:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:598
		{
			yylex.(*parser).unexpected("label set", "\",\" or \"}\"")
			yyVAL.lblList = yyDollar[1].lblList
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:603
		{
			yyVAL.label = labels.Label{Name: yyDollar[1].item.Val, Value: yylex.(*parser).unquoteString(yyDollar[3].item.Val)}
		}
	case 130:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:605
		{
			yylex.(*parser).unexpected("label set", "string")
			yyVAL.label = labels.Label{}
		}
	case 131:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:607
		{
			yylex.(*parser).unexpected("label set", "\"=\"")
			yyVAL.label = labels.Label{}
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:609
		{
			yylex.(*parser).unexpected("label set", "identifier or \"}\"")
			yyVAL.label = labels.Label{}
		}
	case 133:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:617
		{
			yylex.(*parser).generatedParserResult = &seriesDescription{
				labels: yyDollar[1].labels,
				values: yyDollar[2].series,
			}
		}
	case 134:
		yyDollar = yyS[yypt-0 : yypt+1]
//line letheql/parser/generated_parser.y:626
		{
			yyVAL.series = []SequenceValue{}
		}
	case 135:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:628
		{
			yyVAL.series = append(yyDollar[1].series, yyDollar[3].series...)
		}
	case 136:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:630
		{
			yyVAL.series = yyDollar[1].series
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:632
		{
			yylex.(*parser).unexpected("series values", "")
			yyVAL.series = nil
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:636
		{
			yyVAL.series = []SequenceValue{{Omitted: true}}
		}
	case 139:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:638
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i < yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Omitted: true})
			}
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:645
		{
			yyVAL.series = []SequenceValue{{Value: yyDollar[1].float}}
		}
	case 141:
		yyDollar = yyS[yypt-3 : yypt+1]
//line letheql/parser/generated_parser.y:647
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i <= yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Value: yyDollar[1].float})
			}
		}
	case 142:
		yyDollar = yyS[yypt-4 : yypt+1]
//line letheql/parser/generated_parser.y:654
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i <= yyDollar[4].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Value: yyDollar[1].float})
				yyDollar[1].float += yyDollar[2].float
			}
		}
	case 143:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:664
		{
			if yyDollar[1].item.Val != "stale" {
				yylex.(*parser).unexpected("series values", "number or \"stale\"")
			}
			yyVAL.float = math.Float64frombits(value.StaleNaN)
		}
	case 193:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:695
		{
			yyVAL.node = &NumberLiteral{
				Val:      yylex.(*parser).number(yyDollar[1].item.Val),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 194:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:703
		{
			yyVAL.float = yylex.(*parser).number(yyDollar[1].item.Val)
		}
	case 195:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:705
		{
			yyVAL.float = yyDollar[2].float
		}
	case 196:
		yyDollar = yyS[yypt-2 : yypt+1]
//line letheql/parser/generated_parser.y:706
		{
			yyVAL.float = -yyDollar[2].float
		}
	case 199:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:712
		{
			var err error
			yyVAL.uint, err = strconv.ParseUint(yyDollar[1].item.Val, 10, 64)
			if err != nil {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "invalid repetition in series values: %s", err)
			}
		}
	case 200:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:722
		{
			var err error
			yyVAL.duration, err = parseDuration(yyDollar[1].item.Val)
			if err != nil {
				yylex.(*parser).addParseErr(yyDollar[1].item.PositionRange(), err)
			}
		}
	case 201:
		yyDollar = yyS[yypt-1 : yypt+1]
//line letheql/parser/generated_parser.y:733
		{
			yyVAL.node = &StringLiteral{
				Val:      yylex.(*parser).unquoteString(yyDollar[1].item.Val),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 202:
		yyDollar = yyS[yypt-0 : yypt+1]
//line letheql/parser/generated_parser.y:746
		{
			yyVAL.duration = 0
		}
	case 204:
		yyDollar = yyS[yypt-0 : yypt+1]
//line letheql/parser/generated_parser.y:750
		{
			yyVAL.strings = nil
		}
	}
	goto yystack /* stack new state and value */
}
