name: Enhancement Tracking Issue
description: Provide supporting details for a feature in development
labels: feature
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
      description: |
        Feature request
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true
