name: pull-request
on:
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: read
  pull-requests: write

jobs:

  go-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: '.'
        gofmt-flags: '-l -d'


  goimports:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Jerome1337/goimports-action@v1.0.3

  go-vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
    - uses: actions/checkout@v3
    - run: go vet ./...

  staticcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2022.1.3"

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --timeout 5m

  go-test-failfast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
    - uses: actions/checkout@v3
    - run: go test -race -failfast ./...

  go-test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
    - uses: actions/checkout@v3
    - run: go test -race -covermode atomic -coverprofile=coverage.out ./...
    - uses: codecov/codecov-action@v3
    # error parsing coverage: inconsistent NumStmt: changed from 1 to 2 --- https://github.com/golang/go/issues/45361
    #- run: go install github.com/mattn/goveralls@latest
    #- run: goveralls -coverprofile=coverage.out -service=github
    #  env:
    #    COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  go-licenses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
    - uses: actions/checkout@v3
    - run: go install github.com/google/go-licenses@v1.6.0    
    - run: go-licenses check .

  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        build-args: |
          VERSION=development
